"""Problem 45 - Project Euler

Triangular, pentagonal, and hexagonal

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
  | Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
  | Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
  | Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""
from itertools import count

from utils.mathex import triagonal, is_pentagonal, is_hexagonal


class Problem45(object):
    @staticmethod
    def solve():
        for n in count(286):
            v = triagonal(n)
            if is_pentagonal(v) and is_hexagonal(v):
                return v

    @staticmethod
    def get_tests():
        return [(None, 1533776805)]


if __name__ == '__main__':
    print("The answer is", Problem45.solve())
